### PR TITLE
Update TCA to 0.45.0

### PR DESCRIPTION
**Pull request by yermukhanbet**
Update TCA to 0.45.0 so TCA dependency in Santa can be updated as well.

### CODE REVIEW

**Comment by SongJiyeon** [comment]
👍 no issue with new version?

**Comment by yermukhanbet** [comment]
> 👍 no issue with new version?

I checked by adding TCALogsSheetKit dependency by branch (infra/update-TCA), no issues!

Toeic branch with updating TCA can be found in the following link: 

https://github.com/riiid/toeic-ios/tree/feature/update-TCA

**Review by tisohjung — APPROVED** [review]
👍

**Review by SongJiyeon — APPROVED** [review]
작업 감사합니다 🌷

**Comment by korJAEYOUNGYUN** [comment]
ReducerProtocol을 사용할 수는 없을까요?

AnyReducer에 이렇게 나와있네요
`This API has been soft-deprecated in favor of ``ReducerProtocol``.`

**Comment by yermukhanbet** [comment]
> ReducerProtocol을 사용할 수는 없을까요?
> 
> AnyReducer에 이렇게 나와있네요 `` This API has been soft-deprecated in favor of ``ReducerProtocol``. `` https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift

deprecated: 9999.0 있어서 그 warning이 안와야되는 것 같아요

**Comment by yermukhanbet** [comment]
> ReducerProtocol을 사용할 수는 없을까요?
> 
> AnyReducer에 이렇게 나와있네요 `` This API has been soft-deprecated in favor of ``ReducerProtocol``. `` https://github.com/pointfreeco/swift-composable-architecture/blob/main/Sources/ComposableArchitecture/Reducer/AnyReducer/AnyReducer.swift

ReducerProtocol을도 사용 할수 잇는대, 다른 branch에서 수정 하면 더 좋을 것 같아요. 
AnyReducer 아직도 production에 있어서 괜찮은 것 같아요! 
어떻게 생각 하세요?

**Review by korJAEYOUNGYUN — APPROVED** [review]
좋아요!

**Pull request merged**
